### ISSUE TITLE
water.jpg not found

### ISSUE THREAD

**Issue by samadivk** [Hirato/lamiae#9]
None of the water materials work on my Lubuntu 14.04 64bit machine. Lamiae raises an error saying that  water.jpg is not found. When I convert water.png in the media/textures folder to a jpeg, it still doesn't work. Please fix this, Lamiae is amazing otherwise.

**Comment by Hirato** [comment]
Fixed in 5b564983f6e73195999c28c5a6050c6a4acd87c3
It should find the texture now, though amusingly I have never seen this error.

**Comment by samadivk** [comment]
It still doesn't show up... I wonder what's going on.

**Comment by samadivk** [comment]
Here's what I get if I replace one of the built in textures with a conversion of water.png, and the normalmap with watern.jpg
![2015-02-20-122142_2304x1024_scrot](https://cloud.githubusercontent.com/assets/2990223/6286078/680de0f0-b8fb-11e4-8ad9-08c7db296fe8.png)

**Comment by Hirato** [comment]
Your screenshot makes it look as though it failed to load the normal, as the diffuse texture is there.
It should work if you revert your changes to `default_map_settings.cfg` and restore the original textures.

**Comment by samadivk** [comment]
I haven't changed `default_map_settings.cfg`

**Comment by Hirato** [comment]
You'll have to get me your logs, and your config file.
Since you're on Linux, the log would be what it prints to to the console when you run it.
and your configs would be `init.cfg` and `rpg_config.cfg` inside `~/.lamiae` - post these as gists


But it should be enough to just restore the original files; I don't have any files on my system that should be on the repo but aren't.

I'd make a backup (if I changed any of the included files) and then run `git reset --hard origin`, and I'd also do a `git pull` for safe measure.
